# Generated by Django 3.2.7 on 2021-10-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='numero',
            new_name='comuna',
        ),
    ]
