# Generated by Django 3.2.7 on 2021-10-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_rename_numero_estacionamiento_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='estacionamientos'),
        ),
    ]
